import { CardData } from "@/app/@types";

export const coursesData: CardData[] = [
  {
    courseId: 2,
    courseImageUrl: "/cardBg.webp",
    instructorName: "Maria Silva",
    userImageUrl: "/cardUser.jpeg",
    courseLevel: "Beginner",
    coursePrice: 12.0,
    courseStarNumber: 4,
    courseTitle: "Introduction to UX Designer",
    courseTotalTime: "8h 10m",
    category: "DESIGNER",
  },
  {
    courseId: 5,
    courseImageUrl: "/cardBg.webp",
    instructorName: "Maria Silva",
    userImageUrl: "/cardUser.jpeg",
    courseLevel: "Beginner",
    coursePrice: 13.0,
    courseStarNumber: 4,
    courseTitle: "Introduction to databases",
    courseTotalTime: "8h 10m",
    category: "DESIGNER",
  },
  {
    courseId: 8,
    courseImageUrl: "/cardBg.webp",
    instructorName: "Maria Silva",
    userImageUrl: "/cardUser.jpeg",
    courseLevel: "Beginner",
    coursePrice: 30.0,
    courseStarNumber: 4,
    courseTitle: "Datalake",
    courseTotalTime: "8h 10m",
    category: "DESIGNER",
  },
  {
    courseId: 9,
    courseImageUrl: "/cardBg.webp",
    instructorName: "Maria Silva",
    userImageUrl: "/cardUser.jpeg",
    courseLevel: "Beginner",
    coursePrice: 15.0,
    courseStarNumber: 4,
    courseTitle: "Introduction to Photoshop",
    courseTotalTime: "8h 10m",
    category: "DESIGNER",
  },
  {
    courseId: 3,
    courseImageUrl: "/cardBg.webp",
    instructorName: "Pedro Santos",
    userImageUrl: "/cardUser.jpeg",
    courseLevel: "Intermediate",
    coursePrice: 19.9,
    courseStarNumber: 3,
    courseTitle: "Web Development with React",
    courseTotalTime: "10h 30m",
    category: "DEVELOPMENT",
  },
  {
    courseId: 4,
    courseImageUrl: "/cardBg.webp",
    instructorName: "Ana Souza",
    userImageUrl: "/cardUser.jpeg",
    courseLevel: "Advance",
    coursePrice: 25.0,
    courseStarNumber: 5,
    courseTitle: "Digital Marketing Strategies",
    courseTotalTime: "12h 15m",
    category: "BUSINESS",
  },
  {
    courseId: 11,
    courseImageUrl: "/cardBg.webp",
    instructorName: "Pedro Santos",
    userImageUrl: "/cardUser.jpeg",
    courseLevel: "Intermediate",
    coursePrice: 25.0,
    courseStarNumber: 5,
    courseTitle: "React Native for Mobile Development",
    courseTotalTime: "10h 30m",
    category: "DEVELOPMENT",
  },
  {
    courseId: 12,
    courseImageUrl: "/cardBg.webp",
    instructorName: "Ana Costa",
    userImageUrl: "/cardUser.jpeg",
    courseLevel: "Advance",
    coursePrice: 35.0,
    courseStarNumber: 4,
    courseTitle: "Business Analytics with Excel",
    courseTotalTime: "12h 15m",
    category: "BUSINESS",
  },
  {
    courseId: 13,
    courseImageUrl: "/cardBg.webp",
    instructorName: "João Silva",
    userImageUrl: "/cardUser.jpeg",
    courseLevel: "Beginner",
    coursePrice: 20.0,
    courseStarNumber: 3,
    courseTitle: "Digital Photography for Beginners",
    courseTotalTime: "6h 45m",
    category: "PHOTOGRAPHY",
  },
  {
    courseId: 14,
    courseImageUrl: "/cardBg.webp",
    instructorName: "Luiza Souza",
    userImageUrl: "/cardUser.jpeg",
    courseLevel: "Intermediate",
    coursePrice: 30.0,
    courseStarNumber: 4,
    courseTitle: "Adobe Illustrator for Graphic Design",
    courseTotalTime: "9h 20m",
    category: "DESIGNER",
  },
  {
    courseId: 15,
    courseImageUrl: "/cardBg.webp",
    instructorName: "Carlos Lima",
    userImageUrl: "/cardUser.jpeg",
    courseLevel: "Advance",
    coursePrice: 40.0,
    courseStarNumber: 5,
    courseTitle: "Machine Learning with Python",
    courseTotalTime: "14h 10m",
    category: "TECNOLOGY",
  },
  {
    courseId: 16,
    courseImageUrl: "/cardBg.webp",
    instructorName: "Julia Oliveira",
    userImageUrl: "/cardUser.jpeg",
    courseLevel: "Beginner",
    coursePrice: 10.0,
    courseStarNumber: 3,
    courseTitle: "Basic English for Travelers",
    courseTotalTime: "4h 30m",
    category: "ALL",
  },
  {
    courseId: 17,
    courseImageUrl: "/cardBg.webp",
    instructorName: "Ricardo Dias",
    userImageUrl: "/cardUser.jpeg",
    courseLevel: "Intermediate",
    coursePrice: 20.0,
    courseStarNumber: 4,
    courseTitle: "Project Management with Scrum",
    courseTotalTime: "8h 40m",
    category: "MANAGEMENT",
  },
  {
    courseId: 18,
    courseImageUrl: "/cardBg.webp",
    instructorName: "Fernanda Rocha",
    userImageUrl: "/cardUser.jpeg",
    courseLevel: "Advance",
    coursePrice: 50.0,
    courseStarNumber: 5,
    courseTitle: "Web Development with Django",
    courseTotalTime: "16h 20m",
    category: "DEVELOPMENT",
  },
  {
    courseId: 19,
    courseImageUrl: "/cardBg.webp",
    instructorName: "Bruno Alves",
    userImageUrl: "/cardUser.jpeg",
    courseLevel: "Beginner",
    coursePrice: 15.0,
    courseStarNumber: 3,
    courseTitle: "Social Media Marketing",
    courseTotalTime: "5h 50m",
    category: "BUSINESS",
  },
  {
    courseId: 20,
    courseImageUrl: "/cardBg.webp",
    instructorName: "Leticia Santos",
    userImageUrl: "/cardUser.jpeg",
    courseLevel: "Intermediate",
    coursePrice: 25.0,
    courseStarNumber: 4,
    courseTitle: "Photoshop for Photographers",
    courseTotalTime: "10h 15m",
    category: "PHOTOGRAPHY",
  },
];
