import { CardData } from "@/app/@types";

export const coursesData: CardData[] = [
  {
    courseId: 2,
    courseImageUrl: "/cardBg.webp",
    instructorName: "Maria Silva",
    userImageUrl: "/cardUser.jpeg",
    courseLevel: "Iniciante",
    coursePrice: 12.0,
    courseStarNumber: 4,
    courseTitle: "Introdução ao Designer de Experiência do Usuário",
    courseTotalTime: "8h 10m",
    category: "DESIGNER",
  },
  {
    courseId: 5,
    courseImageUrl: "/cardBg.webp",
    instructorName: "Maria Silva",
    userImageUrl: "/cardUser.jpeg",
    courseLevel: "Iniciante",
    coursePrice: 13.0,
    courseStarNumber: 4,
    courseTitle: "Introdução a Bancos de Dados",
    courseTotalTime: "8h 10m",
    category: "DESIGNER",
  },
  {
    courseId: 8,
    courseImageUrl: "/cardBg.webp",
    instructorName: "Maria Silva",
    userImageUrl: "/cardUser.jpeg",
    courseLevel: "Iniciante",
    coursePrice: 30.0,
    courseStarNumber: 4,
    courseTitle: "Datalake",
    courseTotalTime: "8h 10m",
    category: "GERENCIAMENTO",
  },
  {
    courseId: 9,
    courseImageUrl: "/cardBg.webp",
    instructorName: "Maria Silva",
    userImageUrl: "/cardUser.jpeg",
    courseLevel: "Iniciante",
    coursePrice: 15.0,
    courseStarNumber: 4,
    courseTitle: "Introdução ao Photoshop",
    courseTotalTime: "8h 10m",
    category: "TECNOLOGIA",
  },
  {
    courseId: 3,
    courseImageUrl: "/cardBg.webp",
    instructorName: "Pedro Santos",
    userImageUrl: "/cardUser.jpeg",
    courseLevel: "Intermediário",
    coursePrice: 19.9,
    courseStarNumber: 3,
    courseTitle: "Desenvolvimento Web com React",
    courseTotalTime: "10h 30m",
    category: "DESENVOLVIMENTO",
  },
  {
    courseId: 4,
    courseImageUrl: "/cardBg.webp",
    instructorName: "Ana Souza",
    userImageUrl: "/cardUser.jpeg",
    courseLevel: "Avançado",
    coursePrice: 25.0,
    courseStarNumber: 5,
    courseTitle: "Estratégias de Marketing Digital",
    courseTotalTime: "12h 15m",
    category: "NEGÓCIOS",
  },
  {
    courseId: 10,
    courseImageUrl: "/cardBg.webp",
    instructorName: "Carlos Oliveira",
    userImageUrl: "/cardUser.jpeg",
    courseLevel: "Iniciante",
    coursePrice: 18.0,
    courseStarNumber: 4,
    courseTitle: "Introdução ao Design de Interfaces",
    courseTotalTime: "7h 45m",
    category: "FOTOGRAFIA",
  },
  {
    courseId: 11,
    courseImageUrl: "/cardBg.webp",
    instructorName: "Ana Souza",
    userImageUrl: "/cardUser.jpeg",
    courseLevel: "Intermediário",
    coursePrice: 22.5,
    courseStarNumber: 4,
    courseTitle: "Desenvolvimento de Aplicativos Móveis",
    courseTotalTime: "9h 20m",
    category: "DESENVOLVIMENTO",
  },
  {
    courseId: 12,
    courseImageUrl: "/cardBg.webp",
    instructorName: "Pedro Santos",
    userImageUrl: "/cardUser.jpeg",
    courseLevel: "Avançado",
    coursePrice: 28.0,
    courseStarNumber: 5,
    courseTitle: "Estratégias de SEO",
    courseTotalTime: "11h 30m",
    category: "NEGÓCIOS",
  },

  {
    courseId: 13,
    courseImageUrl: "/cardBg.webp",
    instructorName: "Laura Oliveira",
    userImageUrl: "/cardUser.jpeg",
    courseLevel: "Iniciante",
    coursePrice: 14.5,
    courseStarNumber: 4,
    courseTitle: "Fundamentos de Ilustração Digital",
    courseTotalTime: "6h 40m",
    category: "DESIGNER",
  },
  {
    courseId: 14,
    courseImageUrl: "/cardBg.webp",
    instructorName: "Rafael Santos",
    userImageUrl: "/cardUser.jpeg",
    courseLevel: "Intermediário",
    coursePrice: 21.0,
    courseStarNumber: 4,
    courseTitle: "Desenvolvimento Front-end com Vue.js",
    courseTotalTime: "9h 50m",
    category: "DESENVOLVIMENTO",
  },
  {
    courseId: 15,
    courseImageUrl: "/cardBg.webp",
    instructorName: "Ana Souza",
    userImageUrl: "/cardUser.jpeg",
    courseLevel: "Avançado",
    coursePrice: 30.0,
    courseStarNumber: 5,
    courseTitle: "Estratégias de Marketing de Conteúdo",
    courseTotalTime: "11h 20m",
    category: "NEGÓCIOS",
  },
  {
    courseId: 16,
    courseImageUrl: "/cardBg.webp",
    instructorName: "Lucas Oliveira",
    userImageUrl: "/cardUser.jpeg",
    courseLevel: "Iniciante",
    coursePrice: 16.0,
    courseStarNumber: 4,
    courseTitle: "Fundamentos de Prototipagem",
    courseTotalTime: "7h 20m",
    category: "DESIGNER",
  },
  {
    courseId: 17,
    courseImageUrl: "/cardBg.webp",
    instructorName: "Fernanda Santos",
    userImageUrl: "/cardUser.jpeg",
    courseLevel: "Intermediário",
    coursePrice: 23.0,
    courseStarNumber: 4,
    courseTitle: "Desenvolvimento Back-end com Node.js",
    courseTotalTime: "9h 30m",
    category: "DESENVOLVIMENTO",
  },
  {
    courseId: 18,
    courseImageUrl: "/cardBg.webp",
    instructorName: "Ana Souza",
    userImageUrl: "/cardUser.jpeg",
    courseLevel: "Avançado",
    coursePrice: 32.0,
    courseStarNumber: 5,
    courseTitle: "Estratégias de E-mail Marketing",
    courseTotalTime: "11h 40m",
    category: "NEGÓCIOS",
  },
];
