import { CardData } from "@/app/@types";

export const coursesData:CardData[] = [
    {
      courseId: 2,
      courseImageUrl: "/cardBg.webp",
      instructorName: "Maria Silva",
      userImageUrl: "/cardUser.jpeg",
      courseLevel: "Beginner",
      coursePrice: "12.00",
      courseStarNumber: 4,
      courseTitle: "Introduction to UX Designer",
      courseTotalTime: "8h 10m",
      category: "DESIGNER",
    },
    {
      courseId: 5,
      courseImageUrl: "/cardBg.webp",
      instructorName: "Maria Silva",
      userImageUrl: "/cardUser.jpeg",
      courseLevel: "Beginner",
      coursePrice: "13.00",
      courseStarNumber: 4,
      courseTitle: "Introduction to databases",
      courseTotalTime: "8h 10m",
      category: "DESIGNER",
    },
    {
      courseId: 8,
      courseImageUrl: "/cardBg.webp",
      instructorName: "Maria Silva",
      userImageUrl: "/cardUser.jpeg",
      courseLevel: "Beginner",
      coursePrice: "30.00",
      courseStarNumber: 4,
      courseTitle: "Datalake",
      courseTotalTime: "8h 10m",
      category: "DESIGNER",
    },
    {
      courseId: 9,
      courseImageUrl: "/cardBg.webp",
      instructorName: "Maria Silva",
      userImageUrl: "/cardUser.jpeg",
      courseLevel: "Beginner",
      coursePrice: "15.00",
      courseStarNumber: 4,
      courseTitle: "Introduction to Photoshop",
      courseTotalTime: "8h 10m",
      category: "DESIGNER",
    },
    {
      courseId: 3,
      courseImageUrl: "/cardBg.webp",
      instructorName: "Pedro Santos",
      userImageUrl: "/cardUser.jpeg",
      courseLevel: "Intermediate",
      coursePrice: "19.90",
      courseStarNumber: 3,
      courseTitle: "Web Development with React",
      courseTotalTime: "10h 30m",
      category: "DEVELOPMENT",
    },
    {
      courseId: 4,
      courseImageUrl: "/cardBg.webp",
      instructorName: "Ana Souza",
      userImageUrl: "/cardUser.jpeg",
      courseLevel: "Advance",
      coursePrice: "25.00",
      courseStarNumber: 5,
      courseTitle: "Digital Marketing Strategies",
      courseTotalTime: "12h 15m",
      category: "BUSINESS",
    },
  ];
  