import type { Metadata } from "next";
import HomeNavbar from "@/components/layout/HomeNavbar";
import Footer from "@/components/layout/Footer";

import { CatergoriesLinkTypes, LinkType } from "../@types";
import SectionContainer from "@/components/Section/SectionContainer";
import CategoriesLinkButtons from "@/components/CategoriesLinkButtons/CategoriesLinkButtons";

export const metadata: Metadata = {
  title: "curso",
  description: "Generated by create next app",
};

const links: LinkType[] = [
  {
    name: "Todos os Cursos",
    path: "/my-courses/all",
  },
  {
    name: "Favoritos",
    path: "/my-courses/stared",
  },
];

const categories: CatergoriesLinkTypes = {
  links: links,
};

export default function CourseLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <HomeNavbar />
      <SectionContainer className="bg-blue-700 mt-0 pt-14  ">
        <div className=" ">
          <h1 className="text-bold text-4xl">Meus cursos</h1>
        </div>
        <CategoriesLinkButtons links={categories.links} />
      </SectionContainer>

      {children}
      <Footer />
    </>
  );
}
