import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import { LayoutProps } from "../../.next/types/app/layout";
import { SessionProvider } from "next-auth/react";
import AuthProvider from "../../providers/AuthProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type PropTypes = LayoutProps;

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="pt-BR">
      <AuthProvider>
        <body className={inter.className}>{children}</body>
      </AuthProvider>
    </html>
  );
}
